# Generated by Django 4.2 on 2023-04-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_jsbusers_subsidiary'),
        ('Book_Meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booked_By', models.EmailField(max_length=254)),
                ('Date', models.DateField(auto_now=True)),
                ('Time_From', models.TimeField()),
                ('Time_End', models.TimeField()),
                ('Room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Book_Meeting.room')),
                ('Status', models.ForeignKey(default='Booked', on_delete=django.db.models.deletion.CASCADE, to='Accounts.status')),
            ],
        ),
    ]
