# Generated by Django 4.2 on 2023-04-19 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Meeting', '0002_bookedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
