# Generated by Django 4.2 on 2023-04-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_jsbusers_subsidiary'),
        ('Book_Meeting', '0003_alter_bookedroom_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Time Slots',
            },
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.status'),
        ),
    ]
