# Generated by Django 4.2 on 2023-04-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Meeting', '0004_timeslot_alter_bookedroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='Time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Book_Meeting.timeslot'),
        ),
    ]
